2025-01-28 19:38:23,062 - ERROR - Timestamp: 2025-01-28T19:38:23.061969
2025-01-28 19:38:23,063 - ERROR - Message: 'source'
2025-01-28 19:38:23,063 - ERROR - Stack Trace:
Traceback (most recent call last):
  File "D:\clean\server\app_server.py", line 82, in chat
    {"source": doc.metadata["source"], "page": doc.metadata["page"]}
               ~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'source'

2025-01-28 19:38:23,063 - ERROR - --------------------------------------------------
